### ISSUE TITLE
MQTT Example

### ISSUE THREAD

**Issue by simaticgio** [nidayand/motor-on-roller-blind-ws#20]
Hi, 
Can you write us an example for open/close payload command? 

I've not to much experience on mqtt message, anyway is a great idea, thank you.

Jhon.

**Comment by martikainen87** [comment]
Here's what I'm using in Home Assistant with MQTT.

```
cover:
  - platform: mqtt
    name: 'MQTT Cover'
    command_topic: '/raw/esp8266/14020384/in'
    state_topic:  '/raw/esp8266/14020384/out'
    value_template: '{{ value_json.position }}'
    payload_on: "0"
    payload_off: "100"
    state_open: "0"
    state_closed: "100"
    payload_close: '100'
    payload_stop: '0'
    optimistic: false
    retain: true
```
